apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespace-openshift-operators
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: 1-infrastructure
  source:
    path: payload/1-infrastructure/namespace/openshift-operators/namespace
    repoURL: https://github.com/divyakamathorg/gitops-test-mq
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences: []
